# Generated by Django 2.1.7 on 2019-03-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('postIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostAlbum')),
            ],
        ),
        migrations.CreateModel(
            name='FileFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('postIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostFree')),
            ],
        ),
        migrations.CreateModel(
            name='FileJokbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('postIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostJokbo')),
            ],
        ),
        migrations.CreateModel(
            name='FileStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('postIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostStudy')),
            ],
        ),
    ]
