# Generated by Django 2.1.7 on 2019-03-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=50)),
                ('parent', models.CharField(default=None, max_length=20)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='PostFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=50)),
                ('parent', models.CharField(default=None, max_length=20)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='PostJokbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=50)),
                ('parent', models.CharField(default=None, max_length=20)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='PostStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=50)),
                ('parent', models.CharField(default=None, max_length=20)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
                ('startDate', models.DateField(verbose_name='date study started')),
                ('endDate', models.DateField(verbose_name='date study ended')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='PostStudyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('studyIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostStudy')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
