# Generated by Django 2.1.7 on 2019-03-26 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=50)),
                ('parent', models.CharField(default=None, max_length=20)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=10)),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
