# Generated by Django 2.1.7 on 2019-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('stuNo', models.IntegerField(default=0)),
                ('phoneNo', models.IntegerField(default=0)),
                ('lastVisited', models.DateTimeField(verbose_name='date last visited')),
                ('isVerified', models.BooleanField(default=False)),
            ],
        ),
    ]
