# Generated by Django 2.1.7 on 2019-03-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190327_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneNum',
            field=models.CharField(default='010-0000-0000', max_length=20),
        ),
    ]
